dist: bionic
addons:
  apt:
    sources:
      - chef-stable-bionic
    packages:
      - chef-workstation

install: skip

env:
  - CHEF_LICENSE=accept

services:
  - docker

env:
  matrix:
    - INSTANCE=default-amazonlinux-2
    - INSTANCE=default-debian-10
    - INSTANCE=default-ubuntu-1804
    - INSTANCE=default-ubuntu-2004
    - INSTANCE=default-ubuntu-1804 CHEF_VERSION=14

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(chef shell-init bash)"
  - chef --version

script: CHEF_LICENSE=accept-no-persist KITCHEN_LOCAL_YAML=kitchen.dokken.yml kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
        - sudo apt-get install build-essential -y
        - sudo gem install yaml-lint mdl
        - yaml-lint -i ./
        - cookstyle .
        - find . -not -path "*/\.*" -type f -iname "*.md" -exec mdl \{\} \+
      env:
        - CHEF_LICENSE=accept
